import mongoose, { mongo } from "mongoose";

const msgschema = new mongoose.Schema({
    senderId:{
        type : mongoose.Schema.Types.ObjectId,
        ref: "User" , // this is giving ref that senderId will we from User 
        required : true 
    },
    receiverId:{
        type : mongoose.Schema.Types.ObjectId, //ObjectIds are unique identifiers automatically generated by MongoDB for each document in a collection
        ref: "User" , // this is giving ref that receiverId will we from User 
        required : true 
    },
    message : {
        type : String , 
        required : true 
    }
},{timestamps : true})

const Message = mongoose.model("Message", msgschema )
export default Message; // this is used in conSchema